CREATE USER testdb IDENTIFIED BY senha_testdb;
GRANT CONNECT, RESOURCE TO testdb;

-- Conectando como o usuário criado
CONNECT testdb/senha_testdb;

-- Criando tabela de exemplo
CREATE TABLE funcionarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(50),
    cargo VARCHAR2(50),
    salario NUMBER,
    PRIMARY KEY (id)
);

-- Inserindo dados de exemplo
INSERT INTO funcionarios (nome, cargo, salario) VALUES ('João Silva', 'Analista', 3500);
INSERT INTO funcionarios (nome, cargo, salario) VALUES ('Maria Oliveira', 'Gerente', 7500);
INSERT INTO funcionarios (nome, cargo, salario) VALUES ('Paulo Santos', 'Desenvolvedor', 5000);
COMMIT;
